import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any

class ReportGenerator:
    @staticmethod
    def generate_financial_report(data: Dict[str, Any], output_path: str) -> str:
        """
        Generate a PDF financial report from the processed data.
        data: result from PDFProcessor + AI Summary
        """
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = styles['Title']
        story.append(Paragraph("BankFusion Financial Summary", title_style))
        story.append(Spacer(1, 12))

        # Metadata
        normal_style = styles['Normal']
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        story.append(Paragraph(f"Generated on: {date_str}", normal_style))
        story.append(Paragraph(f"Bank: {data.get('bankType', 'Unknown')}", normal_style))
        story.append(Paragraph(f"Account: {data.get('accountNumber', 'N/A')}", normal_style))
        story.append(Spacer(1, 24))

        # AI Summary (if available)
        if 'summary' in data:
            story.append(Paragraph("Executive Summary", styles['Heading2']))
            summary_text = data['summary'].get('executive_summary', 'No summary available.')
            story.append(Paragraph(summary_text, normal_style))
            story.append(Spacer(1, 12))

        # Statistics (if available)
        # Assuming data might have stats passed in, or we calculate them?
        # The PDFProcessor returns 'transactionsInserted' and 'totalTransactions'.
        # We might need to fetch the actual transactions or pass stats.
        # For this feature, we'll assume the caller passes a 'stats' object or we rely on summary.
        
        if 'summary' in data:
            story.append(Paragraph("Key Highlights", styles['Heading2']))
            for highlight in data['summary'].get('key_highlights', []):
                story.append(Paragraph(f"• {highlight}", normal_style))
            story.append(Spacer(1, 12))

        # Footer
        story.append(Spacer(1, 24))
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
        story.append(Paragraph("This report was automatically generated by BankFusion Email Automation.", footer_style))

        doc.build(story)
        return output_path
